### ISSUE TITLE
paper(1) manual contains an error message if building without a prior paper having been installed

### ISSUE THREAD

**Issue by ppisar** [rrthomas/paper#5]
If paper is not installed, executing ./src/paper dies like this:

~~~~
$ ./src/paper 
paper: could not read `/etc/paperspecs'
~~~~

As a result, paper(1) manual generated with help2man embeds the error message in place of the SYNOPSIS section, because ./src/paper is executed:

~~~~
NAME
       paper - print paper size information

DESCRIPTION
       paper: could not read `/etc/paperspecs'

       paper  prints  information  about  the given paper sizes, which can include the standard form of its name, its width and height.
       The name is matched case-insensitively, and ignoring spaces.
~~~~

I believe an ideal fix should make ./src/paper runable without existing /etc/paperspec. E.g. by setting XDG_CONFIG_HOME=./src environment variable and changing ./src/paper.in.in code to parse the system paperspec only if the user's paperspec is not good enough. A fix like that would also allow adding some tests, which this software lacks.

**Comment by rrthomas** [comment]
Thanks for the report, a typical annoying bootstrapping problem! I'll look into it soon.

**Comment by rrthomas** [comment]
I've made a fix, which is simply to make `/etc/paperspecs` optional. Can you let me know if you see any remaining problem? I'll file a separate issue about adding tests, and of course if you'd like to provide any (even just statements of test cases) that would be most welcome.

**Comment by ppisar** [comment]
It did not help much:

~~~~
DESCRIPTION
       paper: no paper sizes configured
~~~~

Maybe you should parse the options before parsing the paperspecs files, so
that "./src/paper --help" returns the usage text.

**Comment by rrthomas** [comment]
Thanks, I forgot to test with no user paper sizes.

**Comment by rrthomas** [comment]
Thanks for your suggestion, which I have followed. Is it working for you now?

**Comment by rrthomas** [comment]
Thanks for confirming! I'll make a release.
