### ISSUE TITLE
problems with latest master

### ISSUE THREAD

**Issue by balducci** [rrthomas/paper#9]
hello

after smooth build/install of latest master of paper
(d68ebfad437e39da7cc18c34c6cefbbe3b16cf72, rev.n. 176), I find that
latest psutils (https://github.com/rrthomas/psutils/commits/master, rev.n. 408)
fails on several tests which use the just installed paper:

    ----8<----
    FAIL: tests/psnup-20-1.sh
    FAIL: tests/psnup-20-2.sh
    FAIL: tests/psnup-20-3.sh
    FAIL: tests/psnup-20-4.sh
    FAIL: tests/psnup-20-1-inpaper-A5.sh
    FAIL: tests/psnup-20-1-inpaper-A5-outpaper-A5.sh
    FAIL: tests/psnup-20-1-inpaper-A4-outpaper-A5.sh
    FAIL: tests/psnup-20-2-inpaper-A5.sh
    FAIL: tests/psnup-20-3-inpaper-A5.sh
    FAIL: tests/psnup-20-4-inpaper-A5.sh
    FAIL: tests/psnup-20-3-rotatedleft.sh
    FAIL: tests/psnup-20-3-rotatedright.sh
    FAIL: tests/psnup-20-1-flip.sh
    FAIL: tests/psnup-20-4-flip.sh
    FAIL: tests/psnup-20-4-297mmx210mm.sh
    FAIL: tests/psnup-20-4-columnmajor.sh
    FAIL: tests/psnup-20-4-margin-10.sh
    FAIL: tests/psnup-20-4-border-20.sh
    FAIL: tests/psresize-20-A5.sh
    FAIL: tests/psresize-20-A3.sh
    FAIL: tests/psresize-20-A4.sh
    FAIL: tests/psresize-20-Letter.sh
    FAIL: tests/psresize-20-A5in-A4.sh
    FAIL: tests/psresize-20-A3in-A4.sh
    ---->8----

No test failures whatsoever when building the same rev. of psutils vs
previous git revision of paper
(678b046a6aadcddecd139d73711bdd9790f30d0d, rev.n. 175)

Actually I could find 2 problems in the newly restored C version of
paper (however, after fixing/working around them, psutils' make check
is still showing the above failures)

1. This caused a segfault on my machine and is fixed by:

```
    ----8<----
    diff -c src/paper.c.in.in.FIX_CHAR src/paper.c.in.in
    *** src/paper.c.in.in.FIX_CHAR	Sun Jan 24 16:45:00 2021
    --- src/paper.c.in.in	Sun Jan 24 16:45:00 2021
    ***************
    *** 82,88 ****
          if (p == NULL)
              p = *saveptr;
          /* Skip leading space. */
    !     for (; isspace(p); p++)
              ;
          size_t i = 0;
          /* Find following comma or end of line. */
    --- 82,88 ----
          if (p == NULL)
              p = *saveptr;
          /* Skip leading space. */
    !     for (; isspace(*p); p++)
              ;
          size_t i = 0;
          /* Find following comma or end of line. */
    ---->8----
```

2. when using ```--unit=pt```, the ```unitfactor ``` function is receiving the
whole command line option ```--unit=pt``` instead of only ```pt```, causing a
paper call failure with ```bad unit (valid units: pt, mm, in)```

This is a crude workaround to better demonstrate the problem:

    ----8<----
    diff -c src/paper.c.in.in.FIX_LONGOPT src/paper.c.in.in
    *** src/paper.c.in.in.FIX_LONGOPT	Sun Jan 24 16:45:00 2021
    --- src/paper.c.in.in	Sun Jan 24 16:45:00 2021
    ***************
    *** 371,377 ****
                  opt_size = true;
                  break;
              case 3:
    !             dim = unitfactor(argv[this_optind]);
                  if (dim == 0.0)
                      die("%s", unit_err);
                  break;
    --- 371,379 ----
                  opt_size = true;
                  break;
              case 3:
    !             //dim = unitfactor(argv[this_optind]);
    ! {char *dummy=strtok(argv[this_optind],"=");}
    ! dim = unitfactor(strtok(NULL,"="));
                  if (dim == 0.0)
                      die("%s", unit_err);
                  break;
    ---->8----

I guess that a proper fix would be to adjust the variables involved in
the getopt_long call.

As I said, after fixing 1. and 2. above, psutils tests which use paper
are still failing: didn't find time to dig further

Building with:

```
gcc -v:
    ----8<----
    Using built-in specs.
    COLLECT_GCC=gcc
    COLLECT_LTO_WRAPPER=/opt/stow.d/versions/gcc-10.2.0/usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0/lto-wrapper
    Target: x86_64-pc-linux-gnu
    Configured with: /home/balducci/tmp/install-us-d/gcc-10.2.0.d/gcc-10.2.0/configure --prefix=/opt/stow.d/versions/gcc-10.2.0/usr --libdir=/opt/stow.d/versions/gcc-10.2.0/usr/lib64 --libexecdir=/opt/stow.d/versions/gcc-10.2.0/usr/lib64 --enable-shared --disable-bootstrap --enable-languages=c,c++,objc,fortran --enable-multilib
    Thread model: posix
    Supported LTO compression algorithms: zlib zstd
    gcc version 10.2.0 (GCC) 
    ---->8----
```
paper configured with:
```
    ----8<----
    ./bootstrap --skip-po
    ---->8----
```
and default configure options

psutils bootstrapped and configured as per defaults.

thanks for your valuable work
ciao
-gabriele

**Comment by rrthomas** [comment]
Thanks for the report. I haven't yet been testing the new `paper` with `psutils`, so I'll get to that! Obviously, `paper` master is not yet intended for use!

**Comment by rrthomas** [comment]
I've fixed the two bugs you mentioned; thanks again. I'll leave this issue open until the new paper is tested and working with psutils.

**Comment by balducci** [comment]
> I've fixed the two bugs you mentioned; thanks again. I'll leave this issue open until the new paper is tested and working with psutils.

thank you very much! I'll upgrade when appropriate

**Comment by rrthomas** [comment]
Fixed now; do please confirm!

**Comment by balducci** [comment]
> Fixed now; do please confirm!

confirmed: master paper builds and installs fine; psutils' make check passes with no failures

I thank you very much

ciao
-gabriele
